# Generated by Django 5.0.1 on 2025-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='partner',
            field=models.BooleanField(default=False, verbose_name='Партнер'),
        ),
    ]
