# Generated by Django 5.0.1 on 2025-02-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='output/%Y/%m/%d/', verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
        ),
    ]
