# Generated by Django 5.0.1 on 2024-03-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_source',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Посилання на оригінальну картинку'),
        ),
    ]
