# Generated by Django 5.0.1 on 2024-03-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, upload_to='products/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_source',
            field=models.URLField(blank=True, verbose_name='Посилання на оригінальну картинку'),
        ),
    ]
