# Generated by Django 5.0.1 on 2024-03-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image_alter_product_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='search_query',
            field=models.TextField(blank=True, verbose_name='Пошукові фрази'),
        ),
    ]
