# Generated by Django 5.0.1 on 2024-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_car_brand',
            field=models.BooleanField(default=False, verbose_name='Бренд машины?'),
        ),
    ]
