# Generated by Django 5.0.1 on 2025-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_price_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vin',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Vin'),
        ),
    ]
