# Generated by Django 5.0.1 on 2025-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='source_id',
            field=models.CharField(max_length=500, unique=True, verbose_name='Ідентифікатор у                                                 вигрузці'),
        ),
    ]
