# Generated by Django 5.0.1 on 2025-04-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_1c',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
