# Generated by Django 5.0.1 on 2025-05-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_old',
        ),
        migrations.AddField(
            model_name='product',
            name='price_partner',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ціна оптова'),
        ),
    ]
