# Generated by Django 5.0.1 on 2025-07-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_color_product_parent_product_color_colortranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість'),
        ),
    ]
