# Generated by Django 5.0.1 on 2025-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watermarked',
            field=models.BooleanField(default=False),
        ),
    ]
