# Generated by Django 5.0.1 on 2025-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='liqpay_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('od', 'При отриманні'), ('ol', 'Онлайн')], default='od', max_length=2, verbose_name='Спосіб оплати'),
        ),
    ]
