# Generated by Django 5.0.1 on 2025-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_liqpay_id_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Адреса кур'єрської доставки"),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('nd', 'Самовивіз із Нової пошти'), ('xd', "Кур'єром Нової Пошти"), ('pu', 'Самовивіз')], default='pu', max_length=2, verbose_name='Спосіб доставки'),
        ),
    ]
