# Generated by Django 5.0.1 on 2025-03-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('od', 'При отриманні'), ('ol', 'LiqPay'), ('mb', 'Monobank')], default='od', max_length=2, verbose_name='Спосіб оплати'),
        ),
    ]
