# Generated by Django 5.0.1 on 2025-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='monobank_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
