# Generated by Django 5.0.1 on 2025-04-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_monobank_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ttn',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='ТТН'),
        ),
    ]
