# Generated by Django 5.0.1 on 2025-05-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_ttn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exported',
            field=models.BooleanField(default=False),
        ),
    ]
