# Generated by Django 5.0.1 on 2025-05-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_exported'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOneClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nw', 'Нова заявка'), ('cd', 'Опрацьовано')], default='nw', max_length=2)),
                ('phone', models.CharField(max_length=17, verbose_name='Телефон')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Замовлення в 1 клік',
                'verbose_name_plural': 'Замовлення в 1 клік',
                'ordering': ('-created',),
            },
        ),
    ]
