# Generated by Django 5.0.1 on 2025-05-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderoneclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Ідентифікатор покупця'),
        ),
        migrations.AlterField(
            model_name='orderoneclick',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='orderoneclick',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='orderoneclick',
            name='status',
            field=models.CharField(choices=[('nw', 'Нова заявка'), ('cd', 'Опрацьовано')], default='nw', max_length=2, verbose_name='Статус'),
        ),
    ]
