# Generated by Django 5.0.1 on 2025-06-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_phone_alter_orderoneclick_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dont_callback',
            field=models.BooleanField(default=False, verbose_name='Не турбувати дзвінками'),
        ),
    ]
