# Generated by Django 5.0.1 on 2025-08-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_dont_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='passed_to_google',
            field=models.BooleanField(default=False, verbose_name='Передано в Google'),
        ),
    ]
