# Generated by Django 5.0.1 on 2025-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_passed_to_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='avtoodiler@gmail.com', max_length=254, verbose_name='E-mail'),
        ),
    ]
