# Generated by Django 5.0.1 on 2025-09-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='utm',
            field=models.TextField(blank=True, null=True, verbose_name='UTM мітки'),
        ),
    ]
